FROM nginx:1.17.10

LABEL maintainer="dev@finflux.co"

COPY ./dist/conflux-web /usr/share/nginx/conflux-web
COPY ./docker-files/nginx-with-backend.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]