version: "3"
services:
    confluxweb:
        image: "conflux-web:local-backend"
        ports:
        - "80:80"
        depends_on: 
        - confluxplatform    
    confluxplatform:
        image: "conflux-platform:local"
        ports:
        - "8080:8080"
        environment: 
            CATALINA_OPTS: "
            -DencryptedDataUsingKeyStore=${encryptedDataUsingKeyStore}
            -DgenerateSecretKeyStore=${generateSecretKeyStore}
            -DsecretKeyStorePassword=${secretKeyStorePassword}
            -DnewSecretKeyStorePassword=${newSecretKeyStorePassword}
            -DsecretKeyStoreFilePath=${secretKeyStoreFilePath}
            -Djdbc.url=${jdbcUrl}
            -Ddb.user=${dbUser}
            -Ddb.pass=${dbPassword}
            " 
        depends_on:
        - redis
        - cassandra
    redis:
        image: "redis:latest"
    cassandra:
        image: "cassandra:latest"