version: "3"
services:
    confluxweb:
        image: "conflux-web:local-backend"
        ports:
        - "80:80"
        depends_on: 
        - confluxplatform    
    confluxplatform:
        image: "conflux-platform:local"
        ports:
        - "8080:8080"
        environment: 
            CATALINA_OPTS: "
            -DencryptedDataUsingKeyStore=${encryptedDataUsingKeyStore}
            -DgenerateSecretKeyStore=${generateSecretKeyStore}
            -DsecretKeyStorePassword=${secretKeyStorePassword}
            -DnewSecretKeyStorePassword=${newSecretKeyStorePassword}
            -DsecretKeyStoreFilePath=${secretKeyStoreFilePath}
            -Djdbc.url=${jdbcUrl}
            -Ddb.user=${dbUser}
            -Ddb.pass=${dbPassword}
            " 
        volumes:
        - ./s3data:/root/.mifosx/pentahoReports
        depends_on:
        - s3vol
    s3vol:
        image: elementar/s3-volume
        command: /data s3://finflux-uat-public/pentaho-reports/
        volumes:
        - ./s3data:/data
        environment:
        - AWS_ACCESS_KEY_ID=${accessKey}
        - AWS_SECRET_ACCESS_KEY=${secretKey}    